{
 "title": "System",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Docker Container Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state)(engine_daemon_container_states_containers{})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(mountpoint) (node_filesystem_free_bytes{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "Total" },
    { "expr": "node_memory_MemFree_bytes{}", "legendFormat": "Free" },
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(mode) (irate(node_cpu_seconds_total{mode != \"idle\"}[5m])) > 0",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "avg by(phase) (probe_http_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mountpoint) (node_filesystem_free_bytes{})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mountpoint) (node_filesystem_free_bytes{})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Website Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SSL",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(instance) (probe_http_ssl)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}